{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9d428c4f",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import os\n",
    "from datetime import datetime\n",
    "\n",
    "# === Config ===\n",
    "st.set_page_config(page_title=\"Cowrie ML Firewall Dashboard\", layout=\"wide\")\n",
    "st.title(\"Cowrie Honeypot - ML Intrusion Detection Dashboard\")\n",
    "\n",
    "# === 1. Live Logs View ===\n",
    "st.header(\"Live Logs View\")\n",
    "if os.path.exists(\"cron_output.log\"):\n",
    "    with open(\"cron_output.log\", \"r\") as f:\n",
    "        logs = f.read()\n",
    "    st.text_area(\"Cron Job Output\", logs, height=250)\n",
    "else:\n",
    "    st.warning(\"cron_output.log not found.\")\n",
    "\n",
    "# === 2. Model Results Summary ===\n",
    "st.header(\"Model Results Summary\")\n",
    "if os.path.exists(\"malicious_ips.txt\"):\n",
    "    with open(\"malicious_ips.txt\", \"r\") as f:\n",
    "        malicious_ips = [line.strip() for line in f if line.strip()]\n",
    "    st.metric(\"Detected Malicious IPs\", len(malicious_ips))\n",
    "else:\n",
    "    st.warning(\"malicious_ips.txt not found.\")\n",
    "\n",
    "# === 3. Show Malicious IPs List ===\n",
    "st.header(\"Malicious IPs List\")\n",
    "if \"malicious_ips\" in locals() and malicious_ips:\n",
    "    st.dataframe(pd.DataFrame(malicious_ips, columns=[\"Blocked IPs\"]))\n",
    "else:\n",
    "    st.info(\"No malicious IPs detected yet.\")\n",
    "\n",
    "# === 4. Firewall Status ===\n",
    "st.header(\"Firewall Status\")\n",
    "if os.path.exists(\"mikrotik_log.txt\"):\n",
    "    with open(\"mikrotik_log.txt\", \"r\") as f:\n",
    "        lines = f.readlines()\n",
    "        last_update = lines[-1] if lines else \"No updates yet.\"\n",
    "    st.text(f\"Last Rule Triggered:\\n{last_update}\")\n",
    "else:\n",
    "    st.warning(\"mikrotik_log.txt not found.\")\n",
    "\n",
    "# === 5. Send Email Alert Manually ===\n",
    "st.header(\"Manual Email Alert\")\n",
    "if st.button(\"Send Test Alert Email\"):\n",
    "    from send_alert_email import send_email_alert\n",
    "    if \"malicious_ips\" in locals() and malicious_ips:\n",
    "        send_email_alert(malicious_ips)\n",
    "        st.success(\"Email sent!\")\n",
    "    else:\n",
    "        st.error(\"No malicious IPs available to send.\")\n",
    "\n",
    "# === 6. Upload New Cowrie Log File ===\n",
    "st.header(\"Upload New Cowrie Log\")\n",
    "uploaded = st.file_uploader(\"Upload cowrie.json\", type=\"json\")\n",
    "if uploaded:\n",
    "    with open(\"cowrie.json\", \"wb\") as f:\n",
    "        f.write(uploaded.getvalue())\n",
    "    st.success(\"Uploaded and replaced cowrie.json!\")\n",
    "\n",
    "# === 7. Manual Session Test ===\n",
    "st.header(\"Test Single Session\")\n",
    "test_cmd = st.text_input(\"Enter Command Sequence (e.g. wget http://...)\", \"\")\n",
    "if st.button(\"Predict\"):\n",
    "    if any(kw in test_cmd.lower() for kw in [\"wget\", \"curl\", \"nc\", \"ftp\", \"payload\"]):\n",
    "        st.error(\"Detected as Malicious\")\n",
    "    else:\n",
    "        st.success(\"Detected as Benign\")\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
