{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "953558d8",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import json\n",
    "import re\n",
    "\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.metrics import classification_report\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "\n",
    "# === 1. Parse Cowrie JSON to DataFrame ===\n",
    "def load_sessions_from_json(json_path):\n",
    "    \"\"\"\n",
    "    Parses a Cowrie JSON log file line by line to extract session information.\n",
    "    \"\"\"\n",
    "    sessions = []\n",
    "    with open(json_path, \"r\") as f:\n",
    "        for line in f:\n",
    "            try:\n",
    "                data = json.loads(line)\n",
    "                if data.get(\"eventid\") == \"cowrie.session.connect\":\n",
    "                    session = {\n",
    "                        \"session\": data[\"session\"],\n",
    "                        \"src_ip\": data[\"src_ip\"],\n",
    "                        \"start_time\": data[\"timestamp\"]\n",
    "                    }\n",
    "                    sessions.append(session)\n",
    "                elif data.get(\"eventid\") == \"cowrie.session.closed\":\n",
    "                    for s in sessions:\n",
    "                        if s[\"session\"] == data[\"session\"]:\n",
    "                            s[\"end_time\"] = data[\"timestamp\"]\n",
    "                elif data.get(\"eventid\") == \"cowrie.command.input\":\n",
    "                    for s in sessions:\n",
    "                        if s[\"session\"] == data[\"session\"]:\n",
    "                            s.setdefault(\"commands\", []).append(data[\"input\"])\n",
    "            except json.JSONDecodeError:\n",
    "                continue\n",
    "    return pd.DataFrame(sessions)\n",
    "\n",
    "# Load Cowrie directory\n",
    "df = load_sessions_from_json(\"cowrie.json\")\n",
    "\n",
    "# === 2. Feature Engineering ===\n",
    "df[\"commands\"] = df[\"commands\"].apply(lambda x: x if isinstance(x, list) else [])\n",
    "df[\"command_sequence\"] = df[\"commands\"].apply(lambda cmds: \" && \".join(cmds))\n",
    "df[\"command_count\"] = df[\"commands\"].apply(len)\n",
    "df[\"input_token_count\"] = df[\"commands\"].apply(lambda cmds: sum(len(c.split()) for c in cmds))\n",
    "df[\"unique_commands\"] = df[\"commands\"].apply(lambda cmds: len(set(cmds)))\n",
    "df[\"end_time\"] = pd.to_datetime(df[\"end_time\"])\n",
    "df[\"start_time\"] = pd.to_datetime(df[\"start_time\"])\n",
    "df[\"duration\"] = (df[\"end_time\"] - df[\"start_time\"]).dt.total_seconds().fillna(0)\n",
    "df[\"has_malicious_keyword\"] = df[\"command_sequence\"].str.contains(\n",
    "    \"wget|curl|nc|ftp|tftp|payload\", case=False, na=False\n",
    ").astype(int)\n",
    "df[\"label\"] = ((df[\"command_count\"] > 0) & (df[\"has_malicious_keyword\"] == 1)).astype(int)\n",
    "\n",
    "# === 3. ML Model Training + Detection ===\n",
    "df[\"original_index\"] = df.index\n",
    "df.dropna(subset=[\"src_ip\", \"duration\"], inplace=True)\n",
    "df[\"protocol\"] = \"ssh\"  # Placeholder if not captured\n",
    "\n",
    "# Define features (X) and target (y)\n",
    "X = df[[\"duration\", \"input_token_count\", \"unique_commands\",\n",
    "        \"has_malicious_keyword\", \"original_index\"]].copy()\n",
    "y = df[\"label\"]\n",
    "\n",
    "# Handle the case of an empty DataFrame after filtering\n",
    "if X.empty:\n",
    "    print(\"Warning: No data available for model training after preprocessing. Exiting.\")\n",
    "    exit()\n",
    "\n",
    "# Split the data into training and testing sets\n",
    "X_train, X_test, y_train, y_test = train_test_split(\n",
    "    X.drop(columns=[\"original_index\"]), y, test_size=0.2, random_state=42\n",
    ")\n",
    "\n",
    "# Train the RandomForestClassifier model\n",
    "rf = RandomForestClassifier(n_estimators=100, random_state=42)\n",
    "rf.fit(X_train, y_train)\n",
    "\n",
    "# Make predictions on the test set\n",
    "y_pred = rf.predict(X_test)\n",
    "\n",
    "# Map predictions back to the original DataFrame\n",
    "test_indices = X_test.index\n",
    "X_test_with_meta = df.loc[test_indices].copy()\n",
    "X_test_with_meta[\"predicted_label\"] = y_pred\n",
    "\n",
    "# === 4. Hybrid IP Detection ===\n",
    "# Get IPs identified as malicious by the ML model\n",
    "ml_ips = set(X_test_with_meta[X_test_with_meta[\"predicted_label\"] == 1][\"src_ip\"])\n",
    "# Get IPs identified by the simple keyword-based approach\n",
    "keyword_ips = set(df[df[\"has_malicious_keyword\"] == 1][\"src_ip\"])\n",
    "# Combine both sets to get all detected malicious IPs\n",
    "all_malicious_ips = sorted(ml_ips.union(keyword_ips))\n",
    "\n",
    "# === 5. Save output ===\n",
    "with open(\"malicious_ips.txt\", \"w\") as f:\n",
    "    for ip in all_malicious_ips:\n",
    "        f.write(ip + \"\\n\")\n",
    "\n",
    "print(f\"Detected and saved {len(all_malicious_ips)} malicious IPs.\")\n",
    "\n",
    "# === 6. Send Email Alert ===\n",
    "from send_alert_email import send_email_alert\n",
    "\n",
    "with open(\"malicious_ips.txt\") as f:\n",
    "    ip_list = [line.strip() for line in f if line.strip()]\n",
    "\n",
    "if ip_list:\n",
    "    send_email_alert(ip_list)\n",
    "else:\n",
    "    print(\"No malicious IPs to alert on.\")\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
